export default function catchError(err: any) {
  console.log('❌ ERROR:', err.message)
}
